---
- summary: |
    Не полный перевод сайта 
  environment: |
    Google Chrome   144.0.7559.97 (официальная сборка) (64 бит)
    Windows 10 22H2 (сборка 19045.6456)
  steps-to-reproduce: |
    1. Зайти на страницу https://products-store.hexlet.app/
    2. Нажать "Language"
    3. Выбрать Русский язык
  expected-result: |
    Страница полностью переводится на Русский язык
  actual-result: |
    Страница переводится частично на Русский язык , описание товаров по прежнему на английском языке 

    
- summary: |
    Сайты выдает раазный список товаров
  environment: |
    Google Chrome   144.0.7559.97 (официальная сборка) (64 бит)
    Windows 10 22H2 (сборка 19045.6456)
  steps-to-reproduce: |
    1. Зайти на страницу https://products-store.hexlet.app/
    2. 6 раз кликнуть "Next"
    3. 6 раз кликнуть "Previous"
  expected-result: |
    Вернется список товаров который был на первой странице
  actual-result: |
    Показывает другие товары на на всех страницах
    
- summary: |
    Поиск по сайту
  environment: |
    Google Chrome   144.0.7559.97 (официальная сборка) (64 бит)
    Windows 10 22H2 (сборка 19045.6456)
  steps-to-reproduce: |
    1. Зайти на страницу https://products-store.hexlet.app/
    2. Написать в поиске "Rolex"
  expected-result: |
    Список товаров с названием "Rolex"
  actual-result: |
    Поиск произходит только по странице , если на странице нет товара Rolex то поиск покажет "Nothing found!" но в магазине они есть

- summary: |
    Сумма заказа
  environment: |
    Google Chrome   144.0.7559.97 (официальная сборка) (64 бит)
    Windows 10 22H2 (сборка 19045.6456)
  steps-to-reproduce: |
    1. Зайти на страницу https://products-store.hexlet.app/
    2. Выбрать тавар 
    3. Кликнуть "В карзину" 2 раза
    4. Кликнуть "Карзина"
  expected-result: |
    Сумма товаров карзине должна соответствовать колличеству товаров
  actual-result: |
    Сумма товаров расчитывается не верно 

- summary: |
    Отображение сайта на мобильном устройстве
  environment: |
    Google Chrome   144.0.7559.97 (официальная сборка) (64 бит)
    Windows 10 22H2 (сборка 19045.6456)
  steps-to-reproduce: |
    1. Зайти на страницу https://products-store.hexlet.app/
    2. открыть DevTools 
    3. Выбрать "Dimensions: Iphone SE
    4. Кликнуть "Карзина"
  expected-result: |
    Должна отобразиться сайт адаптированная под мобильное устройство
  actual-result: |
    Интерфес сайта съехал
    
