---
- summary: |
    Поиск товара по ключевому слову
  status: pass
  
- summary: |
    Поиск товара по категориям
  status: pass

- summary: |
    Поиск товара по фильтру "Производитель"
  status: pass

- summary: |
    Поиск товара по фильтру "В наличии"
  status: pass

- summary: |
    Поиск товара по фильтру "Цена" 
  status: fail

- summary: |
    Добвление товара в карзину 
  status: pass

- summary: |
    Смена языка интерфейса 
  status: fail

- summary: |
    Просмотр таваров 
  status: pass

- summary: |
    Сброс фильтров 
  status: fail

- summary: |
    Выбор количества товаров
  status: fail

- summary: |
    Сумма товаров в карзине
  status: pass

bugreports:
- summary: |
    Сбрасывается язык
  environment: |
    Google Chrome   144.0.7559.97 (официальная сборка) (64 бит)
    Windows 10 22H2 (сборка 19045.6456)
  steps-to-reproduce: |
    1. Зайти на страницу https://products-store.hexlet.app/
    2. Нажать "Language"
    3. Выбрать Русский язык
    4. Нажать "Магазин"
  expected-result: |
    Страница остается на русском языке
  actual-result: |
    Страница переводится обратно на английский язык 
- summary: |
    Не работает чистка карзины
  environment: |
    Google Chrome   144.0.7559.97 (официальная сборка) (64 бит)
    Windows 10 22H2 (сборка 19045.6456)
  steps-to-reproduce: |
    1. Зайти на страницу https://products-store.hexlet.app/
    2. Нажать "В карзину" на любом товаре 
    3. Нажать "Карзина"
    4. Нажать "Очистить карзину"
    5. Нажать "Магазин"
  expected-result: |
    ОТкроется главная страница при это карзина должна быть пуста 
  actual-result: |
    Открывается главная страница и удаленные тавары возвращаются в карзину

- summary: |
    Фмльтр по цене работает не корректно
  environment: |
    Google Chrome   144.0.7559.97 (официальная сборка) (64 бит)
    Windows 10 22H2 (сборка 19045.6456)
  steps-to-reproduce: |
    1. Зайти на страницу https://products-store.hexlet.app/
    2. В фильтре цена до написать 9
  expected-result: |
    Откроется список товаров с ценой до 9
  actual-result: |
    Фильтр не учитывает цену со скидкой , отображаются товары с ценой до 9 без скидки 

- summary: |
    Фмльтр по цене работает не корректно
  environment: |
    Google Chrome   144.0.7559.97 (официальная сборка) (64 бит)
    Windows 10 22H2 (сборка 19045.6456)
  steps-to-reproduce: |
    1. Зайти на страницу https://products-store.hexlet.app/
    2. В фильтре цена от написать 9
    3. В фильтре цена до написать 9
  expected-result: |
    Откроется список товаров с ценой от 9 и до 9
  actual-result: |
    Открывается список товаров с разными ценами каторые не входят в промежуток от 9 до 9
    
