---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность переключить язык интерфейса
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен иметь локализацию (перевод) на русский и английский языки
  - Сайт должен быть доступен для пользователей без использования VPN (прямой доступ из сети Интернет)
  
implicit:
  - На сайте долджна быть форма регистраци
  - В форме регистрации должны быть пункты: Логи, имя пользователя , номер телефона , пароль , подтверждения пароля 
  - Логин должен проверяться на уже существующий
  - Имя пользователя должно быть написано одним словом 
  - Имя пользователя должно быть написано кирилецей
  - Номер телефона должен содержать только цифры и не более 12 символов  
  - Номер телефона должен иметь не более 12 символов
  - Номер телефона должен начинаться с цифры или знака "+"
  - Пароль должен содержать не менее 6 символов 
  - Подтверждение пароля должно совпадать с паролем 
  - На сайте должна быть форма авторизации пользователя
  - В форме регистрации должны быть пункты: логин , пароль 
  
