---
- summary: |
    Поиск товара по ключевому слову
  requirement: |
    Пользователь должен иметь возможность искать товары по ключевому слову 
  prerequisites: |
    Открыт сайт на главной странице https://products-store.hexlet.app/
  test-data:
  steps:
    - Нажимаем по окну "Поиск"
    - Вводим запрос , например : "Lip"
  expected-result: |
    Пользователь должен увидеть список товаров соответстующему запросу
    
    - summary: |
    Поиск товара по категориям
  requirement: |
    Пользователь должен иметь возможность искать товары по категориям
  prerequisites: |
    Открыт сайт на главной странице https://products-store.hexlet.app/
  test-data:
  steps:
    - Нажимаем по кнопке "Категория"
    - Выбираем одну из 
  expected-result: |
    Пользователь должен увидеть список товаров соответстующему запросу
